{
	"openapi": "3.0.0",
	"info": {
		"title": "PedjuangIlmu API",
		"version": "1.0.0",
		"description": "API for managing courses"
	},
	"components": {
		"securitySchemes": {
			"BearerAuth": {
				"type": "apiKey",
				"name": "Authorization",
				"in": "header"
			}
		}
	},
	"servers": [
		{
			"url": "/api/v1/"
		}
	],
	"tags": [
		{
			"name": "Authentication",
			"description": "User Auth API"
		},
		{
			"name": "Profiles",
			"description": "User Profiles API"
		},
		{
			"name": "Category",
			"description": "Categories API"
		},
		{
			"name": "Course",
			"description": "Courses API"
		},
		{
			"name": "Chapter",
			"description": "Chapters API"
		},
		{
			"name": "Course Material",
			"description": "Materials API"
		},
		{
			"name": "Payment Menthod",
			"description": "Payment Methods API"
		},
		{
			"name": "User Progress",
			"description": "User Progress API"
		},
		{
			"name": "Order Course",
			"description": "Orders API"
		}
	],
	"paths": {
		"/courses": {
			"get": {
				"summary": "Get a list of courses with pagination, search, and filter",
				"tags": ["Course"],
				"parameters": [
					{
						"name": "page",
						"in": "query",
						"description": "Page number for pagination",
						"schema": {
							"type": "integer",
							"default": 1
						}
					},
					{
						"name": "search",
						"in": "query",
						"description": "Search query for courses",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "rating",
						"in": "query",
						"description": "Minimum rating for courses",
						"schema": {
							"type": "integer"
						}
					},
					{
						"name": "price",
						"in": "query",
						"description": "Maximum price for courses",
						"schema": {
							"type": "number"
						}
					},
					{
						"name": "newlyReleased",
						"in": "query",
						"description": "Filter newly released courses",
						"schema": {
							"type": "boolean"
						}
					},
					{
						"name": "category",
						"in": "query",
						"description": "Category ID for filtering courses",
						"schema": {
							"type": "integer"
						}
					},
					{
						"name": "typeCourse",
						"in": "query",
						"description": "Type of course for filtering",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "level",
						"in": "query",
						"description": "Level of courses for filtering",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"status": "success",
									"message": "Data for all courses successfully obtained!",
									"courses": [],
									"pagination": {
										"currentPage": 1,
										"pageSize": 10,
										"totalItems": 0,
										"totalPages": 0
									}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/courses/create": {
			"post": {
				"summary": "Create a new course",
				"tags": ["Course"],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"example": {
								"title": "Course Title",
								"description": "Description of course",
								"price": 200000,
								"type_course": "free",
								"level": "pemula",
								"url_group": "www.discord.com/backend2",
								"category_id": 2
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"message": "Created!",
									"categories": {}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/courses/detail/{id}": {
			"get": {
				"summary": "Get details of a specific course",
				"tags": ["Course"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of the course",
						"required": true,
						"schema": {
							"type": "integer"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"message": "Success for retrieving course data",
									"courses": {}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/courses/update/{id}": {
			"put": {
				"summary": "Update a course by ID",
				"tags": ["Course"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of the course to be updated",
						"required": true,
						"schema": {
							"type": "integer",
							"format": "int64"
						}
					}
				],
				"requestBody": {
					"description": "Updated course data",
					"required": true,
					"content": {
						"application/json": {
							"example": {
								"title": "Updated Title",
								"description": "Updated Description",
								"price": 29.99,
								"type_course": "premium",
								"level": "lanjutan",
								"url_group": "https://updated-url.com",
								"category_id": 1
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"message": "Course updated successfully",
									"course": {
										"id": 1,
										"title": "Updated Title",
										"description": "Updated Description",
										"price": 29.99,
										"type_course": "premium",
										"level": "advanced",
										"url_group": "https://updated-url.com",
										"createdAt": "2023-12-01T12:34:56.789Z",
										"updatedAt": "2023-12-02T12:34:56.789Z",
										"category_id": 1
									}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/courses/delete/{id}": {
			"delete": {
				"summary": "Delete a course by ID",
				"tags": ["Course"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of the course to be deleted",
						"required": true,
						"schema": {
							"type": "integer",
							"format": "int64"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"message": "Course deleted successfully!"
								}
							}
						}
					},
					"404": {
						"description": "Course not found",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"message": "Course not found"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},

		"/chapters": {
			"get": {
				"summary": "Get all chapters",
				"tags": ["Chapter"],
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"data": []
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/chapters/create": {
			"post": {
				"summary": "Create a new chapter",
				"tags": ["Chapter"],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"example": {
								"title": "Chapter 1",
								"course_id": 1,
								"content": "Chapter content here"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"data": {}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/chapters/{id}": {
			"get": {
				"tags": ["Chapter"],
				"summary": "Get details of a specific chapter",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of the chapter",
						"required": true,
						"schema": {
							"type": "integer"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"data": {}
								}
							}
						}
					},
					"404": {
						"description": "Chapter not found",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"message": "Chapter not found"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/chapters/update/{id}": {
			"put": {
				"tags": ["Chapter"],
				"summary": "Update a specific chapter",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of the chapter",
						"required": true,
						"schema": {
							"type": "integer"
						}
					}
				],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"example": {
								"title": "Updated Chapter Title",
								"content": "Updated chapter content"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"data": {}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/chapters/delete{id}": {
			"delete": {
				"tags": ["Chapter"],
				"summary": "Delete a specific chapter",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of the chapter",
						"required": true,
						"schema": {
							"type": "integer"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"message": "Chapter deleted successfully"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},

		"/course-materials": {
			"get": {
				"summary": "Get a list of all course materials",
				"tags": ["Course Material"],
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"status": true,
									"data": [
										{
											"id": 1,
											"chapter_id": 2,
											"course_id": 3,
											"title": "Material Title",
											"content": "Material Content",
											"url_video": "https://video-url.com",
											"createdAt": "2023-12-01T12:34:56.789Z",
											"updatedAt": "2023-12-02T12:34:56.789Z"
										}
									]
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/course-materials/create": {
			"post": {
				"summary": "Create a new course material",
				"tags": ["Course Material"],
				"requestBody": {
					"description": "Data for the new course material",
					"required": true,
					"content": {
						"application/json": {
							"example": {
								"chapter_id": 1,
								"course_id": 1,
								"title": "New Material Title",
								"content": "Content of the new material",
								"url_video": "https://example.com/video"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"data": {
										"id": 1,
										"chapter_id": 1,
										"course_id": 1,
										"title": "New Material Title",
										"content": "Content of the new material",
										"url_video": "https://example.com/video",
										"createdAt": "2023-12-01T12:34:56.789Z"
									}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/course-materials/{id}": {
			"get": {
				"summary": "Get details of a course material by ID",
				"tags": ["Course Material"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of the course material to be retrieved",
						"required": true,
						"schema": {
							"type": "integer",
							"format": "int64"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"data": {
										"id": 1,
										"chapter_id": 1,
										"course_id": 1,
										"title": "Course Material Title",
										"content": "Course Material Content",
										"url_video": "https://example.com/video",
										"createdAt": "2023-12-01T12:34:56.789Z",
										"updatedAt": "2023-12-02T12:34:56.789Z",
										"chapters": {
											"id": 1,
											"title": "Chapter Title"
										},
										"courses": {
											"id": 1,
											"title": "Course Title"
										},
										"userProgress": {}
									}
								}
							}
						}
					},
					"404": {
						"description": "Course Material not found",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"message": "Course Material not found"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/course-materials/update/{id}": {
			"put": {
				"summary": "Update course material by ID",
				"tags": ["Course Material"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of the course material to be updated",
						"required": true,
						"schema": {
							"type": "integer",
							"format": "int64"
						}
					}
				],
				"requestBody": {
					"description": "Updated course material data",
					"required": true,
					"content": {
						"application/json": {
							"example": {
								"title": "Updated Material Title",
								"content": "Updated material content",
								"url_video": "https://updated-video-url.com"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"data": {
										"id": 1,
										"title": "Updated Material Title",
										"content": "Updated material content",
										"url_video": "https://updated-video-url.com",
										"createdAt": "2023-12-01T12:34:56.789Z",
										"updatedAt": "2023-12-02T12:34:56.789Z"
									}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/course-materials/delete/{id}": {
			"delete": {
				"summary": "Delete course materials by ID",
				"tags": ["Course Material"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of the course materials to be deleted",
						"required": true,
						"schema": {
							"type": "integer",
							"format": "int64"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"message": "Course Materials deleted successfully"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},

		"/categories": {
			"get": {
				"summary": "Get list of categories",
				"tags": ["Category"],
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"categories": []
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/categories/create": {
			"post": {
				"summary": "Create a new category",
				"tags": ["Category"],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"example": {
								"title": "Category Title"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Successful response",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"message": "Created!",
									"categories": {}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/categories/detail/{id}": {
			"get": {
				"summary": "Get details of a category by ID",
				"tags": ["Category"],
				"parameters": [
					{
						"in": "path",
						"name": "id",
						"required": true,
						"schema": {
							"type": "integer"
						},
						"description": "ID of the category"
					}
				],
				"responses": {
					"200": {
						"description": "Category details retrieved successfully",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"categories": {
										"id": 1,
										"title": "Category Title"
									}
								}
							}
						}
					},
					"404": {
						"description": "Category not found",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"message": "Category not found"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/categories/update/{id}": {
			"put": {
				"summary": "Update category by ID",
				"tags": ["Category"],
				"parameters": [
					{
						"in": "path",
						"name": "id",
						"required": true,
						"schema": {
							"type": "integer"
						},
						"description": "ID of the category"
					}
				],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"example": {
								"title": "Updated Category Title"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Category updated successfully",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"data": {
										"id": 1,
										"title": "Updated Category Title",
										"createdAt": "2023-12-01T12:34:56.789Z",
										"updatedAt": "2023-12-01T12:34:56.789Z"
									}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/categories/delete/{id}": {
			"delete": {
				"summary": "Delete category by ID",
				"tags": ["Category"],
				"parameters": [
					{
						"in": "path",
						"name": "id",
						"required": true,
						"schema": {
							"type": "integer"
						},
						"description": "ID of the category"
					}
				],
				"responses": {
					"200": {
						"description": "Category deleted successfully",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"message": "Category deleted successfully"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},

		"/auth/register": {
			"post": {
				"summary": "Register a new user",
				"tags": ["Authentication"],
				"requestBody": {
					"content": {
						"application/json": {
							"example": {
								"username": "john_doe",
								"email": "john.doe@example.com",
								"password": "securepassword",
								"role": "user",
								"profile": {
									"name": "John Doe",
									"no_telp": "1234567890",
									"avatar": "https://example.com/avatar.jpg",
									"city": "City",
									"country": "Country"
								}
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "User registered successfully",
						"content": {
							"application/json": {
								"example": {
									"user": {
										"id": 1,
										"username": "john_doe",
										"email": "john.doe@example.com",
										"role": "user",
										"is_verified": false,
										"createdAt": "2023-12-01T12:34:56.789Z",
										"updatedAt": "2023-12-01T12:34:56.789Z"
									},
									"profile": {
										"id": 1,
										"user_id": 1,
										"name": "John Doe",
										"no_telp": "1234567890",
										"avatar": "https://example.com/avatar.jpg",
										"city": "City",
										"country": "Country",
										"createdAt": "2023-12-01T12:34:56.789Z",
										"updatedAt": "2023-12-01T12:34:56.789Z"
									},
									"message": "Registered Successful. Email verification sent."
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/auth/login": {
			"post": {
				"summary": "Login",
				"tags": ["Authentication"],
				"requestBody": {
					"content": {
						"application/json": {
							"example": {
								"email": "john.doe@example.com",
								"password": "securepassword"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Successful login",
						"content": {
							"application/json": {
								"example": {
									"data": {
										"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM4ODM0MjA2LCJleHAiOjE2Mzg4MzcyMDZ9.-jPwHzoJ7QqhzrcOrskJzHGqIYiCpALFk7G3AdUupJc"
									}
								}
							}
						}
					},
					"403": {
						"description": "Invalid Credentials",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Invalid Credentials"
								}
							}
						}
					},
					"404": {
						"description": "Email not registered",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Your email is not registered in our system"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/auth/reset-password": {
			"post": {
				"summary": "Request password reset",
				"tags": ["Authentication"],
				"requestBody": {
					"content": {
						"application/json": {
							"example": {
								"email": "john.doe@example.com"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Password reset link sent successfully",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"successMessage": "Password reset link was sent to your email!"
								}
							}
						}
					},
					"404": {
						"description": "User not found",
						"content": {
							"application/json": {
								"example": {
									"error": true,
									"errorMessage": "User not found!"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"error": true,
									"errorMessage": "An error occurred"
								}
							}
						}
					}
				}
			}
		},
		"/auth/set-password": {
			"post": {
				"summary": "Set new password after reset",
				"tags": ["Authentication"],
				"requestBody": {
					"content": {
						"application/json": {
							"example": {
								"key": "reset_key_token",
								"password": "newpassword"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Password reset successful",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"successMessage": "Password reset was successful!"
								}
							}
						}
					},
					"400": {
						"description": "Invalid or expired reset key",
						"content": {
							"application/json": {
								"example": {
									"error": true,
									"errorMessage": "Invalid or expired reset key!"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"error": true,
									"errorMessage": "An error occurred"
								}
							}
						}
					}
				}
			}
		},
		"/auth/verify-email": {
			"post": {
				"summary": "Verify user email",
				"tags": ["Authentication"],
				"requestBody": {
					"content": {
						"application/json": {
							"example": {
								"email": "john.doe@example.com",
								"otp": "123456"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Email verification successful",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"successMessage": "Email verification successful"
								}
							}
						}
					},
					"400": {
						"description": "Invalid OTP",
						"content": {
							"application/json": {
								"example": {
									"error": true,
									"errorMessage": "Invalid OTP"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"error": true,
									"errorMessage": "An error occurred during email verification"
								}
							}
						}
					}
				}
			}
		},
		"/auth/resend-otp": {
			"post": {
				"summary": "Resend email verification OTP",
				"tags": ["Authentication"],
				"requestBody": {
					"content": {
						"application/json": {
							"example": {
								"email": "john.doe@example.com"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "New OTP sent successfully",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"successMessage": "New OTP sent successfully"
								}
							}
						}
					},
					"400": {
						"description": "User not found or email is already verified",
						"content": {
							"application/json": {
								"example": {
									"error": true,
									"errorMessage": "User not found or email is already verified"
								}
							}
						}
					},
					"500": {
						"description": "Failed to resend OTP",
						"content": {
							"application/json": {
								"example": {
									"error": true,
									"errorMessage": "Failed to resend OTP"
								}
							}
						}
					}
				}
			}
		},

		"/profiles/my-profile": {
			"get": {
				"summary": "Get user profile",
				"tags": ["Profiles"],
				"security": [
					{
						"BearerAuth": []
					}
				],
				"responses": {
					"200": {
						"description": "User profile fetched successfully",
						"content": {
							"application/json": {
								"example": {
									"id": 1,
									"user_id": 1,
									"name": "John Doe",
									"no_telp": "1234567890",
									"avatar": "https://example.com/avatar.jpg",
									"city": "City",
									"country": "Country",
									"createdAt": "2023-12-01T12:34:56.789Z",
									"updatedAt": "2023-12-01T12:34:56.789Z",
									"user": {
										"id": 1,
										"username": "john_doe",
										"email": "john.doe@example.com",
										"role": "user",
										"is_verified": true,
										"createdAt": "2023-12-01T12:34:56.789Z",
										"updatedAt": "2023-12-01T12:34:56.789Z"
									}
								}
							}
						}
					},
					"404": {
						"description": "User not found",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "User not found!"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/profiles/update-profile": {
			"put": {
				"summary": "Update user profile",
				"tags": ["Profiles"],
				"security": [
					{
						"BearerAuth": []
					}
				],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"example": {
								"name": "John Doe",
								"no_telp": "1234567890",
								"avatar": "https://example.com/avatar.jpg",
								"city": "City",
								"country": "Country"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Profile updated successfully",
						"content": {
							"application/json": {
								"example": {
									"id": 1,
									"user_id": 1,
									"name": "John Doe",
									"no_telp": "1234567890",
									"avatar": "https://example.com/avatar.jpg",
									"city": "City",
									"country": "Country",
									"createdAt": "2023-12-01T12:34:56.789Z",
									"updatedAt": "2023-12-01T12:34:56.789Z",
									"user": {
										"id": 1,
										"username": "john_doe",
										"email": "john.doe@example.com",
										"role": "user",
										"is_verified": true,
										"createdAt": "2023-12-01T12:34:56.789Z",
										"updatedAt": "2023-12-01T12:34:56.789Z"
									}
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		},
		"/profiles/update-password": {
			"put": {
				"summary": "Update user password",
				"tags": ["Profiles"],
				"security": [
					{
						"BearerAuth": []
					}
				],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"example": {
								"currentPassword": "current_password",
								"newPassword": "new_password"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Password updated successfully",
						"content": {
							"application/json": {
								"example": {
									"success": true,
									"message": "Password updated successfully"
								}
							}
						}
					},
					"404": {
						"description": "User not found",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "User not found"
								}
							}
						}
					},
					"400": {
						"description": "Invalid current password",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Invalid current password"
								}
							}
						}
					},
					"500": {
						"description": "Internal Server Error",
						"content": {
							"application/json": {
								"example": {
									"success": false,
									"error": "Internal Server Error"
								}
							}
						}
					}
				}
			}
		}
	}
}
